apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: mysql
    environment: dev
spec:
  selector:
    app: mysql
    environment: dev
  ports:
    - port: 3306
  clusterIP: None
